<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Description>Theme extension for Avalonia.Controls.DataGrid in Nox theme style.</Description>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" />
        <PackageReference Include="Avalonia.Controls.DataGrid" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Nox.Avalonia\Nox.Avalonia.csproj" />
    </ItemGroup>
</Project>