<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <AvaloniaVersion>12.1.1</AvaloniaVersion>
    <DockVersion>12.1.0</DockVersion>
  </PropertyGroup>

  <ItemGroup>
    <!-- Core Library dependencies -->
    <PackageVersion Include="Avalonia" Version="$(AvaloniaVersion)" />
    <PackageVersion Include="Avalonia.Fonts.Inter" Version="$(AvaloniaVersion)" />
    <PackageVersion Include="Avalonia.Themes.Simple" Version="$(AvaloniaVersion)" />

    <!-- Demo Application dependencies -->
    <PackageVersion Include="Avalonia.Desktop" Version="$(AvaloniaVersion)" />
    <PackageVersion Include="Avalonia.Controls.DataGrid" Version="12.1.0" />
    <PackageVersion Include="AvaloniaUI.DiagnosticsSupport" Version="2.2.3" />

    <!-- Dock dependencies -->
    <PackageVersion Include="Dock.Avalonia" Version="$(DockVersion)" />
    <PackageVersion Include="Dock.Model" Version="$(DockVersion)" />
    <PackageVersion Include="Dock.Model.Mvvm" Version="$(DockVersion)" />
    <PackageVersion Include="Dock.Avalonia.Themes.Simple" Version="$(DockVersion)" />

    <!-- PropertyGrid dependencies -->
    <PackageVersion Include="bodong.Avalonia.PropertyGrid" Version="12.0.4.1" />
    <PackageVersion Include="bodong.PropertyModels" Version="12.0.0" />
  </ItemGroup>
</Project>